apiVersion: v1
kind: Service
metadata:
  name: nextcloud
  labels:
    name: nextcloud
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
  selector:
    name: nextcloud
